### ISSUE TITLE
Task gettext.extract does not work when used last in an alias

### ISSUE THREAD

**Issue by maufl** [elixir-lang/gettext#104]
I just stumbled upon a problem with the `mix gettext.extract` task. In our `mix.exs` file we define an alias like this:
```
      "gettext.extract": ["custom.gettext.extract", "gettext.extract"]
```
This does not work :( The code gets compiled but the POT file is never written.
However:
```
      "gettext.extract": ["gettext.extract", "custom.gettext.extract"]
```
does work.

Our custom extract task looks like this.
```
  def run(_) do
    node_env = case Application.get_env(:papyrus_psp, :environment) do
      :dev   -> "development"
      :prod  -> "production"
      :test  -> "test"
      _      -> "unknown"
    end

    case Mix.Shell.IO.cmd(command(node_env)) do
      0 -> :ok
      _ -> :error
    end
  end

  defp command(node_env) do
    "NODE_ENV=#{node_env} $(npm bin)/react-gettext-parser --output priv/gettext/react.pot 'web/static/js/**/*.{js,jsx}' '!web/static/js/i18n.js'"
  end
```

It's not really a problem for us, but maybe someone else will run into the same problem, so I wanted to document it here.

**Comment by josevalim** [comment]
Which gettext version? Have you tried the latest? :)

**Comment by maufl** [comment]
Sorry, forgot to mention the version. We're on 0.11, as far as I can see that's the latest version.

**Comment by whatyouhide** [comment]
I'll look into this @maufl, thanks for the report. Btw just for safety, when things don't work as expected always try out master as well as the latest version, we may have fixed bugs there (but I don't think this is the case) 😺

**Comment by whatyouhide** [comment]
I was finally able to reproduce this and I think I know the problem that is causing it (but not the solution 😕). First of all, this is not reproducible using custom tasks as functions (instead of compiled Mix tasks), e.g., this doesn't reproduce the problem:

```elixir
def project() do
  [app: ...,
   aliases: ["gettext.extract": [&custom_gettext_extract/1, "gettext.extract"]]]
end
```

The example above works fine. It's reproducible however when the custom task is a compiled Mix task, e.g.:

```elixir
def project() do
  [app: ...,
   aliases: ["gettext.extract": ["custom.gettext.extract", "gettext.extract"]]]
end

# In lib/mix/tasks/custom.gettext.extract.ex
defmodule Mix.Tasks.Custom.Gettext.Extract do
  use Mix.Task
  def run(_args), do: :ok
end
```

As you can see, the task can do absolutely nothing and this is still reproducible. What happens is that in the example above, POT files are just not extracted. This happens because [this line](https://github.com/elixir-lang/gettext/blob/330c5d9cfebcea71561eb50c97e05a0d4165e56c/lib/mix/tasks/gettext.extract.ex#L59) returns an empty list of POT files to extract, and going deeper, we just discover that `Gettext.Extractor` (specifically [this line](https://github.com/elixir-lang/gettext/blob/330c5d9cfebcea71561eb50c97e05a0d4165e56c/lib/gettext/extractor.ex#L58)) is never called; this led me to believe that when we call [`force_compile/1` here](https://github.com/elixir-lang/gettext/blob/330c5d9cfebcea71561eb50c97e05a0d4165e56c/lib/mix/tasks/gettext.extract.ex#L58) we don't actually compile anything because everything was compiled in order to run the `custom.gettext.extract` task.

@josevalim I have no idea what's going on but I remember you working on this force-compile stuff, maybe you have an idea of what's going on right off your head? I created [a repo](https://github.com/whatyouhide/gettext_task_alias_bug) for you to reproduce this, you can just run `./test.sh` in it and see if `default.pot` is extracted (it should be).

**Comment by josevalim** [comment]
@whatyouhide you are right. It doesn't run because compile was already invoked. What you could do is to call `Mix.Task.reenable "compile"` as well as traverse all children reenabling them. Here is what Phoenix does in its code reloader: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/code_reloader/server.ex#L107

I don't think we need to reenable them all though, likely just the elixir compiler.
