### ISSUE TITLE
Gettext.extract ignores macro parameters

### ISSUE THREAD

**Issue by syamilmj** [elixir-lang/gettext#141]
It seems that `Gettext.extract` would completely ignore any strings that are part of parameters for a macro. I haven't tried using it as `def` parameters, but I assume the result should be the same.

Here's a little contrived example:

```
foo :one, %{
  two: gettext("Two"),
  three: gettext("Three")
}

defmacro foo(:one, data)
  quote do: unquote(data)
end
```

**Comment by whatyouhide** [comment]
I tried reproducing this with the following complete code sample in a `mix new foo` generated project, in `lib/foo.ex`, with `{:gettext, github: "elixir-lang/master"}` in `mix.exs`:

```elixir
defmodule G do
  use Gettext, otp_app: :foo
end

defmodule Macros do
  defmacro macro(:one, data) do
    quote do: unquote(data)
  end
end

defmodule Foo do
  import Macros
  import G

  def foo() do
    macro(:one, %{
      two: gettext("Two"),
      three: gettext("Three"),
    })
  end
end
```

and the extraction work. Could you provide a complete example, with instructions on how to set it up, and that uses Gettext master please? :)

**Comment by syamilmj** [comment]
Yep, I meant `mix gettext.extract`. Sorry for the confusion! :)

Here's another example:

```
defmodule G do
  use Gettext, otp_app: :gettext_macro_bug
end

defmodule Macros do
  defmacro macro(:one, data) do
    quote do: unquote(data)
  end

  defmacro macro2(action, data) do
    data = Macro.to_string(data)

    quote do
      def unquote(:"#{action}_method")(conn) do
        var = "abc"
        Code.eval_string(unquote(data), [var: var], __ENV__)
      end
    end
  end
end

defmodule Foo do
  import Macros
  import G

  macro(:one, %{
    two: gettext("Two"),
    three: gettext("Three"),
  })

  macro2(:one, %{
    two: gettext("Four"),
    three: gettext("Five %{var}", var: var),
  })
end
```

In this example, `macro/2` works as you'd expected, but `macro2/2` doesn't.

**Comment by josevalim** [comment]
@syamilmj you almost never use Code.eval_quoted in Elixir, especially not inside macros. You are converting code to string at compile time then you are evaluating the code at runtime. You likely made the code order of magnitudes slower because, instead of allowing Elixir to compile the code, you are converting it to a string that needs to be parsed, validated and evaluated at runtime.

And that's why Gettext no longer "works". There is no gettext macro being invoked in the second example, after all, you converted the code to a string. `gettext` is only called at runtime and by then extraction has long finished.

**Comment by syamilmj** [comment]
Appreciate that Jose! Learned a new thing today about Elixir today :)

**Comment by syamilmj** [comment]
Putting this link to recent commit as reference to what Jose said above: https://github.com/elixir-lang/elixir/commit/08fd26984316eb26b0f6d28efe35527eba08a338
