### ISSUE TITLE
Chinese language code

### ISSUE THREAD

**Issue by zhangsoledad** [elixir-lang/gettext#80]
There is a difference between Simplified Chinese and Traditional Chinese, zh can't distinguish
 the difference, usually we use `zh_CN` for  Simplified Chinese, `zh_TW` for Traditional Chinese, like  `en_US` and `en_GB`. 
also see https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

**Comment by josevalim** [comment]
Thank you @zhangsoledad!

@whatyouhide I think we should make the plural rules all prefix based. For example, instead of `"zn"` we should use `"zn" <> _`. The only exception of course are the ones which we already specify in the "x_Y"  format. We also need to make sure they come in the proper order. Thoughts?

**Comment by whatyouhide** [comment]
@josevalim using `"..." <> _` sounds good to me. Today, we only have one locale `x_*` that has different pluralization rules than their `x` counterpart, which is `pt`/`pt_BR`; first of all, you can confirm that these two indeed have different pluralization rules. Then, I think a good way to approach this is just to define the clauses for specific `x_*` locales on the top so that they're always picked up first, and then all the `x <> _` clauses.

Note to self: we even have `es` and `es_AR` today as separate locales, but we could get rid of this difference in case we implement this as they have the same pluralization rules. Wdyt?

**Comment by josevalim** [comment]
Awesome. I will check about the portuguese rule. I have always spoken the same as in Portugal but Brazil is a bit country. :P

**Comment by josevalim** [comment]
@whatyouhide let's remove both `es_AR` and `pt_BR`. We can always revisit later on.
