### ISSUE TITLE
Default pluralizer does not have fallback for unknown locales

### ISSUE THREAD

**Issue by maufl** [elixir-lang/gettext#87]
Hi, it's me again ^^
The documentation says:

> Locale
> 
> At runtime, all gettext-related functions and macros that do not explicitely take a locale as an argument read the locale from Gettext.get_locale/1. The locale can be set with Gettext.put_locale/2. Locales are expressed as strings (like "en" or "fr"); they can be arbitrary strings as long as they match a directory name.

However, I just found that this locale will be passed to `Gettext.Plural.plural` if no other pluralizer is configured. I get a `no function clause matching` for the locale `nb-no`.

I think there should be a catch all clause to avoid problems when people use strange locales.

**Comment by whatyouhide** [comment]
Ok, note to self (so that I understand this better :smiley:):

1. A user wants to use a locale that `Gettext.Plural` doesn't cover, e.g., `nb-no`.
2. They add the `nb-no/LC_MESSAGES/*.po` translation files, hence...
3. ...a `nb-no` clause is generated for the `l(n)gettext` functions in each backend.
4. This clause is hit when translating `nb-no` messages, so we hit [these lines](https://github.com/elixir-lang/gettext/blob/784d97eb6d897a89843c896c8d5d3cb1be9081f4/lib/gettext/compiler.ex#L250-L256), where `@plural_forms.plural("nb-no", n)` is called.
5. `Gettext.Plural` doesn't cover `"nb-no"`, thus function clause error :)

@josevalim thoughts on what to do here? We could have a match-all clause in `Gettext.Plural` and warn, returning English pluralization rules in the meantime, or a match-all clause that simply raises. Wdyt?

**Comment by josevalim** [comment]
It is probably best to raise with a good error message and instructions on how to install your own plural rules. Right?

**Comment by whatyouhide** [comment]
@josevalim right, I even updated the docs for `Gettext.Plural` some time ago exactly to show how to just add a locale and fallback to `Gettext.Plural` for all others. Will do this in a moment then.

**Comment by whatyouhide** [comment]
@josevalim a small problem arised while implementing this: right now, since we do `locale <> _` for all clauses, I had trouble reproducing this because

```elixir
Gettext.Plural.plural("wat", 1)
```

is fine as we support the `"wa"` locale and have a clause `def plural("wa" <> _)`. Not sure what's the best course of action here: we could have clauses for `"wa_" <> _` instead, but I'm not sure we'd cover all possible locales that way and we'd have to have another clause (without the underscore) for each locale.
I'm afraid if we leave it as `"wa" <> _`, we'll allow very subtle unexpected behaviours. Wdyt?

**Comment by josevalim** [comment]
@whatyouhide what if our catch all clause split on "_" and call it again only with the first part? Alternatively, for every locale, we could generate a clause like this: `def plural("wa_" <> _, n), do: plural("wa", n)`. Thoughts?

**Comment by whatyouhide** [comment]
@josevalim okay, I was writing my smart solution only to find out it's the same as your first solution, only I didn't get your first solution because of markdown being nasty :smile: Yes, let's do

```elixir
def plural("en", ...)
...

def plural(lang_and_locale, n) do
  # if there's a _COUNTRY suffix, re-call plural/2 with just the language
  # otherwise, raise
end
```

**Comment by whatyouhide** [comment]
@josevalim I'm having second thoughts (months later 😄) on this, not sure why we ignored

> It is probably best to raise with a good error message and instructions on how to install your own plural rules. Right?

your comment, which makes very very much sense to me right now 😕

**Comment by josevalim** [comment]
:+1:

**Comment by whatyouhide** [comment]
Nah, it makes sense to drop the region from the locale when pluralizing. Users still have full customizability through `Gettext.Plural` if they want to get into weird stuff. I think many times you would have to implement a `Gettext.Plural` pluralizer that just takes all of the various `en_US`, `en_AU`, and so on to `en` (same for other languages). If there are kinky languages like `pt_BR`, chances are we already handle them correctly.

So,

![](http://i.giphy.com/65NO1TrKrJUT6.gif)
